name: Nightly builds
on:
  schedule:
    - cron: '0 21 * * 1-5' # Run at 9 PM UTC+2 on Weekdays.
jobs:
  build:
    if: github.repository_owner == 'co-cart'
    name: Nightly builds
    strategy:
      fail-fast: false
      matrix:
        build: [master]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.build }}
      - name: Build
        id: build
        uses: co-cart/action-build@v1
      - name: Deploy nightly build
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLUGIN_SLUG: "cart-rest-api-for-woocommerce"
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/49034208/assets{?name,label}
          release_id: 49034208
          asset_path: ${{ steps.build.outputs.zip_path }}
          asset_name: cocart-${{ matrix.build }}-nightly.zip
          asset_content_type: application/zip
          max_releases: 1
  update:
    name: Update nightly tag commit ref
    runs-on: ubuntu-latest
    steps:
      - name: Update nightly tag
        uses: richardsimko/github-tag-action@v1.0.5
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
